In [3]:
from sklearn.cluster import KMeans
from sklearn import preprocessing
import pandas as pd
import numpy as np


# 数据加载

data = pd.read_csv('team_cluster_data.csv', encoding='gbk')

train_x = data[["2019国际排名","2018世界杯排名","2015亚洲杯排名"]]

kmeans = KMeans(n_clusters=3)

# 规范化到 [0,1] 空间

min_max_scaler=preprocessing.MinMaxScaler()

train_x=min_max_scaler.fit_transform(train_x)

#print(train_x)

# kmeans 算法

kmeans.fit(train_x)

predict_y = kmeans.predict(train_x)

# 合并聚类结果，插入到原数据中

result = pd.concat((data,pd.DataFrame(predict_y)),axis=1)

result.rename({0:u'聚类结果'},axis=1,inplace=True)

print(result)

# 将结果导出到CSV文件中

#result.to_csv("team_cluster_result.csv")

        国家  2019国际排名  2018世界杯排名  2015亚洲杯排名  聚类结果
0       中国        73         40          7     2
1       日本        60         15          5     1
2       韩国        61         19          2     1
3       伊朗        34         18          6     1
4       沙特        67         26         10     1
5      伊拉克        91         40          4     2
6      卡塔尔       101         40         13     0
7      阿联酋        81         40          6     2
8   乌兹别克斯坦        88         40          8     2
9       泰国       122         40         17     0
10      越南       102         50         17     0
11      阿曼        87         50         12     0
12      朝鲜       110         50         14     0
13      印尼       164         50         17     0
14      澳洲        40         30          1     1
15     叙利亚        76         40         17     0
16      约旦       118         50          9     0
17     科威特       160         50         15     0


In [7]:
# 使用多种分类器进行MNIST手写数字分类

from sklearn.model_selection import train_test_split

from sklearn import preprocessing

from sklearn.metrics import accuracy_score

from sklearn.datasets import load_digits

from sklearn import svm #SVM

from sklearn.linear_model import LogisticRegression #逻辑回归

from sklearn.tree import DecisionTreeClassifier #决策树

from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB #高斯朴素贝叶斯 GaussianNB/MultinomialNB/BernoulliNB

from sklearn.neighbors import KNeighborsClassifier #KNN

from sklearn.ensemble import  AdaBoostClassifier #AdaBoost

# from xgboost import XGBClassifier #XGBoost

from sklearn.discriminant_analysis import LinearDiscriminantAnalysis  

import matplotlib.pyplot as plt


# 加载数据

digits = load_digits()

data = digits.data

# 数据探索

print('data shape:', data.shape)

# 查看第一幅图像

print(digits.images[0])

# 第一幅图像代表的数字含义

print(digits.target[0])

# 将第一幅图像显示出来

"""

plt.gray()

plt.imshow(digits.images[0])

plt.show()

"""



# 分割数据，将25%的数据作为测试集，其余作为训练集

train_x, test_x, train_y, test_y = train_test_split(data, digits.target, test_size=0.25, random_state=33)

print(train_x.max())

print((train_x>1).sum())

print(train_x.shape[0]*train_x.shape[1])

# 采用Z-Score规范化

ss = preprocessing.StandardScaler()

train_ss_x = ss.fit_transform(train_x)

test_ss_x = ss.transform(test_x)



# 创建LR分类器

lr = LogisticRegression(solver='liblinear', multi_class='auto') #数据集比较小，使用liblinear，数据集大使用 sag或者saga

lr.fit(train_ss_x, train_y)

predict_y=lr.predict(test_ss_x)

print('LR准确率: %0.4lf' % accuracy_score(predict_y, test_y))



# 创建线性 CART决策树分类器

model = DecisionTreeClassifier()

model.fit(train_ss_x,train_y)

predict_y=model.predict(test_ss_x)

print('CART决策树准确率: %0.4lf' %accuracy_score(predict_y,test_y))



# 创建LDA分类器

model = LinearDiscriminantAnalysis(n_components=2)

model.fit(train_ss_x,train_y)

predict_y=model.predict(test_ss_x)

print('LDA准确率: %0.4lf' %accuracy_score(predict_y,test_y))



# 创建贝叶斯分类器

model = GaussianNB()

model.fit(train_x,train_y)

predict_y=model.predict(test_x)

print('朴素贝叶斯准确率: %0.4lf' %accuracy_score(predict_y,test_y))



# 创建SVM分类器

model = svm.SVC(kernel='rbf', C=1.0, gamma='auto')

model.fit(train_ss_x,train_y)

predict_y=model.predict(test_ss_x)

print('SVM准确率: %0.4lf' %accuracy_score(predict_y,test_y))



# 创建KNN分类器

model = KNeighborsClassifier()

model.fit(train_ss_x,train_y)

predict_y=model.predict(test_ss_x)

print('KNN准确率: %0.4lf' %accuracy_score(predict_y,test_y))



# 创建AdaBoost分类器

# 弱分类器

dt_stump = DecisionTreeClassifier(max_depth=5,min_samples_leaf=1)

dt_stump.fit(train_ss_x, train_y)

#dt_stump_err = 1.0-dt_stump.score(test_x, test_y)

# 设置AdaBoost迭代次数

n_estimators=500

model = AdaBoostClassifier(base_estimator=dt_stump,n_estimators=n_estimators)

model.fit(train_ss_x,train_y)

predict_y=model.predict(test_ss_x)

print('AdaBoost准确率: %0.4lf' %accuracy_score(predict_y,test_y))



# 创建XGBoost分类器

# model = XGBClassifier()

# model.fit(train_ss_x,train_y)

# predict_y=model.predict(test_ss_x)

# print('XGBoost准确率: %0.4lf' %accuracy_score(predict_y,test_y))

data shape: (1797, 64)
[[ 0.  0.  5. 13.  9.  1.  0.  0.]
 [ 0.  0. 13. 15. 10. 15.  5.  0.]
 [ 0.  3. 15.  2.  0. 11.  8.  0.]
 [ 0.  4. 12.  0.  0.  8.  8.  0.]
 [ 0.  5.  8.  0.  0.  9.  8.  0.]
 [ 0.  4. 11.  0.  1. 12.  7.  0.]
 [ 0.  2. 14.  5. 10. 12.  0.  0.]
 [ 0.  0.  6. 13. 10.  0.  0.  0.]]
0
16.0
40971
86208
LR准确率: 0.9600
CART决策树准确率: 0.8489
LDA准确率: 0.9378
朴素贝叶斯准确率: 0.8311
SVM准确率: 0.9867
KNN准确率: 0.9756
AdaBoost准确率: 0.9644


In [8]:
# 使用TPOT自动机器学习工具对MNIST进行分类

from tpot import TPOTClassifier

from sklearn.datasets import load_digits

from sklearn.model_selection import train_test_split

import numpy as np



# 加载数据

digits = load_digits()

data = digits.data

print(digits.target)

X_train, X_test, y_train, y_test = train_test_split(digits.data.astype(np.float64),

    digits.target.astype(np.float64), train_size=0.75, test_size=0.25)



tpot = TPOTClassifier(generations=5, population_size=20, verbosity=2)

tpot.fit(X_train, y_train)

print(tpot.score(X_test, y_test))

tpot.export('tpot_mnist_pipeline.py')

[0 1 2 ... 8 9 8]


Generation 1 - Current best internal CV score: 0.9792069392812888
Generation 2 - Current best internal CV score: 0.9792069392812888
Generation 3 - Current best internal CV score: 0.9792124466473909
Generation 4 - Current best internal CV score: 0.9792124466473909
Generation 5 - Current best internal CV score: 0.9792124466473909

Best pipeline: ExtraTreesClassifier(CombineDFs(Nystroem(input_matrix, gamma=0.15000000000000002, kernel=chi2, n_components=4), input_matrix), bootstrap=False, criterion=entropy, max_features=0.3, min_samples_leaf=1, min_samples_split=14, n_estimators=100)
0.9666666666666667


In [3]:
# titanic 数据清洗
import numpy as np

import pandas as pd

from sklearn.tree import DecisionTreeClassifier

from sklearn.feature_extraction import DictVectorizer

from sklearn.model_selection import cross_val_score

from sklearn import metrics

from sklearn.feature_extraction import DictVectorizer



# 数据加载

train_data = pd.read_csv('./train.csv')

test_data = pd.read_csv('./test.csv')

# 数据探索

# 查看train_data信息

#pd.set_option('display.max_columns', None) #显示所有列

print('查看数据信息：列名、非空个数、类型等')

print(train_data.info())

print('-'*30)

print('查看数据摘要')

print(train_data.describe())

print('-'*30)

print('查看离散数据分布')

print(train_data.describe(include=['O']))

print('-'*30)

print('查看前5条数据')

print(train_data.head())

print('-'*30)

print('查看后5条数据')

print(train_data.tail())



# 使用平均年龄来填充年龄中的nan值

train_data['Age'].fillna(train_data['Age'].mean(), inplace=True)

test_data['Age'].fillna(test_data['Age'].mean(),inplace=True)

# 使用票价的均值填充票价中的nan值

train_data['Fare'].fillna(train_data['Fare'].mean(), inplace=True)

test_data['Fare'].fillna(test_data['Fare'].mean(),inplace=True)



print(train_data['Embarked'].value_counts())

# 使用登录最多的港口来填充登录港口的nan值

train_data['Embarked'].fillna('S', inplace=True)

test_data['Embarked'].fillna('S',inplace=True)

# 特征选择

features = ['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked']

train_features = train_data[features]

train_labels = train_data['Survived']

test_features = test_data[features]

print('特征值')

print(train_features)



dvec=DictVectorizer(sparse=False)

train_features=dvec.fit_transform(train_features.to_dict(orient='record'))

print(dvec.feature_names_)

# 构造ID3决策树

clf = DecisionTreeClassifier(criterion='entropy')

# 决策树训练

clf.fit(train_features, train_labels)



test_features=dvec.transform(test_features.to_dict(orient='record'))

# 决策树预测

pred_labels = clf.predict(test_features)



# 得到决策树准确率(基于训练集)

acc_decision_tree = round(clf.score(train_features, train_labels), 6)

print(u'score准确率为 %.4lf' % acc_decision_tree)



# 使用K折交叉验证 统计决策树准确率

print(u'cross_val_score准确率为 %.4lf' % np.mean(cross_val_score(clf, train_features, train_labels, cv=10)))

查看数据信息：列名、非空个数、类型等
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
None
------------------------------
查看数据摘要
       PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642

In [1]:
# stream 数据清洗
import numpy as np 
import pandas as pd 
import random



path = './steam-200k.csv'

df = pd.read_csv(path, header = None, names = ['UserID', 'Game', 'Action', 'Hours', 'Not Needed'])

# 数据探索

print('显示前5条数据')

print(df.head())

print('显示数据大小')

print(df.shape)

# 创建Hours_Played字段，替代原有的Action和Hours，0表示仅购买，大于0表示购买且游戏时长

df['Hours_Played'] = df['Hours'].astype('float32')

# 如果字段Action=purchase，并且Hours=1.0，将设置Hours_Played=0

df.loc[(df['Action'] == 'purchase') & (df['Hours'] == 1.0), 'Hours_Played'] = 0

print(df['Hours_Played'])

print('增加了Hours_Played字段后，数据大小')

print(df.shape)



# 对数据从小到大进行排序, df下标也会发生变化

df.UserID = df.UserID.astype('int')

df = df.sort_values(['UserID', 'Game', 'Hours_Played'], ascending=True)



# 删除重复项，并保留最后一项出现的项（因为最后一项是用户游戏时间，第一项为购买）

clean_df = df.drop_duplicates(['UserID', 'Game'], keep = 'last')

# 去掉不用的列：Action, Hours, Not Needed

clean_df = clean_df.drop(['Action', 'Hours', 'Not Needed'], axis = 1)

print('删除重复项后的数据集：')

print(clean_df)

print(clean_df.head(0))



# 探索下数据集的特征

n_users = len(clean_df.UserID.unique())

n_games = len(clean_df.Game.unique())

print('数据集中包含了 {0} 玩家，{1} 游戏'.format(n_users, n_games))



# 矩阵的稀疏性

sparsity = clean_df.shape[0] / float(n_users * n_games)

print('用户行为矩阵的稀疏性（填充比例）为{:.2%} '.format(sparsity))

显示前5条数据
      UserID                        Game    Action  Hours  Not Needed
0  151603712  The Elder Scrolls V Skyrim  purchase    1.0           0
1  151603712  The Elder Scrolls V Skyrim      play  273.0           0
2  151603712                   Fallout 4  purchase    1.0           0
3  151603712                   Fallout 4      play   87.0           0
4  151603712                       Spore  purchase    1.0           0
显示数据大小
(200000, 5)
0           0.0
1         273.0
2           0.0
3          87.0
4           0.0
          ...  
199995      1.5
199996      0.0
199997      1.5
199998      0.0
199999      1.4
Name: Hours_Played, Length: 200000, dtype: float32
增加了Hours_Played字段后，数据大小
(200000, 6)
删除重复项后的数据集：
           UserID                          Game  Hours_Played
65430        5250                   Alien Swarm           4.9
65424        5250               Cities Skylines         144.0
65435        5250                Counter-Strike           0.0
65436        5250         Coun